config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController

  def index
    @flats = Flat.all
  end

  def show
    @flat = Flat.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/index.html.erb
<div class="m-4">
  <h1>All our Flats</h1>
  <p>All <%= @flats.count%> flats.</p>
</div>

<div class="d-flex p-2 bd-highlight justify-content-around align-items-end">
  <% @flats.each do |flat| %>
    <div class="card" style="width: 18rem;">
      <img class="card-img-top" src="https://cdn.apartmenttherapy.info/image/upload/v1619013756/at/house%20tours/2021-04/Erin%20K/KERR-130-CLARKSON-2R-01-020577-EDIT-WEB.jpg" alt="Card image cap">
      <div class="card-body bg-light">
        <h5 class="card-title"><%= flat.name %></h5>
        <p class="card-text"><%= flat.description %></p>
      </div>
      <div class="d-flex justify-content-center gap-3 bg-white h-100 w-100 py-3">
        <%= link_to 'More Info', flat_path(flat), class: "btn btn-primary" %>
        <%= link_to 'Delete', flat_path(flat), class: "btn btn-primary" %>
      </div>
    </div>
  <% end %>
</div>

app/views/flats/show.html.erb
<h1><%= @flat.name %></h1>

<div class="m-3">
  <p>Number of Guests: <%= @flat.number_of_guests %></p>
  <p>Price/Night: <%= @flat.price_per_night %></p>
  <p>Address: <%= @flat.address %></p>
  <p>Description: <%= @flat.description %></p>
  <%= link_to 'Return to Home Page', flats_path %>
  <br>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>